# Generated by Django 5.0.4 on 2026-06-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('parches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='parches.parche'),
        ),
    ]
