# Generated by Django 5.2.3 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='pay_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('waiting', 'En espera'), ('closed', 'Cerrado')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='evento',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='eventoparticipant',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
