# Generated by Django 5.2.3 on 2026-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_evento_pay_immediately_evento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='eventoparticipant',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
