# Generated by Django 5.2.3 on 2026-07-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_evento_receipt_and_more'),
        ('finanzas', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='destination_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='eventos.evento'),
        ),
    ]
